import Head from 'next/head'
import Categories from '../../components/Categories';
import ProductList from '../../components/ProductList';

const CategoryPage = ({ categories, products }) => {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Categories data={categories} />
        <ProductList data={products} />
      </main>
    </>
  )
}

export default CategoryPage

export async function getStaticPaths() {
  const api = `http://sklepdemo.gocreate.pl/tmp/rest.php`,
    auth = `?auth=coojier6ExaedaiXu6ch`,
    categoriesRes = await fetch(`${api}${auth}&action=categories`),
    categories = await categoriesRes.json();
  const catPaths = [];
  categories.map(cat => {
    catPaths.push({ params: { catId: cat.id.toString() } });
  });

  return {
    paths: catPaths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const api = `http://sklepdemo.gocreate.pl/tmp/rest.php`,
    auth = `?auth=coojier6ExaedaiXu6ch`,
    productsRes = await fetch(`${api}${auth}&action=products&idKat=${params.catId}`),
    categoriesRes = await fetch(`${api}${auth}&action=categories`),
    products = await productsRes.json(),
    categories = await categoriesRes.json();

  return {
    props: {
      products,
      categories,
    },
  }
}