import Head from 'next/head'
import Categories from '../components/Categories';
import ProductList from '../components/ProductList';

export default function Home({ products, categories }) {

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Categories data={categories} />
        <ProductList data={products} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const api = `http://sklepdemo.gocreate.pl/tmp/rest.php`,
    auth = `?auth=coojier6ExaedaiXu6ch`,
    productsRes = await fetch(`${api}${auth}&action=products`),
    categoriesRes = await fetch(`${api}${auth}&action=categories`),
    products = await productsRes.json(),
    categories = await categoriesRes.json();

  return {
    props: {
      products,
      categories,
    },
  }
}
